DROP TABLE T_OWNERS;
DROP TABLE T_OWNERTYPE;
DROP TABLE T_PRICETAVLE;
DROP TABLE T_AREA;
DROP TABLE T_OPERATOR;
DROP TABLE T_ADDRESS;
DROP TABLE T_ACCOUNT;

-- 业主表
CREATE TABLE T_OWNERS(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(30),
ADDRESSID NUMBER,
HOUSENUMBER VARCHAR2(30),
ADDDATE DATE,
OWNERTYPEID NUMBER
);


-- 业主类型表
CREATE TABLE T_OWNERTYPE(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(30)
);

-- 价格表
CREATE TABLE T_PRICETAVLE(
ID NUMBER PRIMARY KEY,
PRICE NUMBER(10, 2),
OWNERTYPEID NUMBER,
MINNUM NUMBER(10,2),
MAXNUM NUMBER(10,2)
);

-- 区域表
CREATE TABLE T_AREA(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(30)
);

-- 收费员表
CREATE TABLE T_OPERATOR(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(30)
);

-- 地址表
CREATE TABLE T_ADDRESS(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(30),
AREAID NUMBER,
OPERATORID NUMBER
);

-- 收费台账表
CREATE TABLE T_ACCOUNT(
ID NUMBER PRIMARY KEY,
OWNERID NUMBER,
OWNERTYPEID NUMBER,
AREAID NUMBER,
YEAR CHAR(4),
MONTH CHAR(2),
NUM0 NUMBER,
NUM1 NUMBER,
USENUM NUMBER,
METERUSERID NUMBER,
NETEDATE DATE,
MONEY NUMBER(10,2),
ISFEE CHAR(1),
FEEDATE DATE,
FEEUSERID NUMBER
);
